services:
  tempo:
    image: grafana/tempo:2.7.0
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - "4318:4318"
      - "3200:3200"
    networks:
      - observability
    user: root

  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-remote-write-receiver"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - observability
    extra_hosts:
      - "host.docker.internal:host-gateway"

  loki:
    image: grafana/loki:3.3.0
    command: ["-config.file=/etc/loki-config.yaml"]
    volumes:
      - ./loki/loki-config.yaml:/etc/loki-config.yaml
      - loki-data:/var/loki
    ports:
      - "3100:3100"
    networks:
      - observability
    user: root

  promtail:
    image: grafana/promtail:latest
    command: ["-config.file=/etc/promtail-config.yaml"]
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail-config.yaml
      - /private/tmp:/var/log/backend
    networks:
      - observability
    user: root

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - ./grafana/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/dashboards/ll-overview.json:/var/lib/grafana/dashboards/ll-overview.json
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - observability

volumes:
  tempo-data:
  loki-data:
  prometheus-data:
  grafana-data:

networks:
  observability:
